name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:20250512

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build
        run: make -j$(nproc) PREFIX="ccache aarch64-none-elf-"

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: sdcard
          path: out/sd

      - name: Upload elf file
        uses: actions/upload-artifact@v4
        with:
          name: ldn_mitm.elf
          path: ldn_mitm/ldn_mitm.elf

      - name: Upload elf file
        uses: actions/upload-artifact@v4
        with:
          name: overlay.elf
          path: overlay/overlay.elf
