name: Build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install depency
        run: |
          wget -q https://wii.leseratte10.de/devkitPro/libnx/libnx-4.8.0-1-any.pkg.tar.zst
          dkp-pacman -U --noconfirm *.zst

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2

      - name: Build
        run: make -j8 PREFIX="ccache aarch64-none-elf-"

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: sdcard
          path: out/sd

      - name: Upload elf file
        uses: actions/upload-artifact@v4
        with:
          name: ldn_mitm.elf
          path: ldn_mitm/ldn_mitm.elf

      - name: Upload elf file
        uses: actions/upload-artifact@v4
        with:
          name: overlay.elf
          path: overlay/overlay.elf
