name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkita64:latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install depency
      run: |
        wget -q https://wii.leseratte10.de/devkitPro/libnx/libnx-4.8.0-1-any.pkg.tar.zst
        dkp-pacman -U --noconfirm *.zst

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
    
    - name: Build
      run: make -j8 PREFIX="ccache aarch64-none-elf-"

    - name: Pack
      run: |
        cd ./out/sd
        sudo zip -r ./ldn_mitm_${{ github.ref_name }}.zip atmosphere switch

    - name: Release and Upload Assets
      uses: softprops/action-gh-release@v2
      with:
        name: ${{ github.ref_name }}
        generate_release_notes: true
        files: out/sd/ldn_mitm_${{ github.ref_name }}.zip
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/${{ github.ref_name }}/total?label=Downloads)
